### ISSUE TITLE
Temporary one-way access to streets is not parsed and included in the routing

### ISSUE THREAD

**Issue by adeveloper-wq** [priobike/priobike-graphhopper-drn#17]
During our test ride we found out that the "Herbert weich…? Straße" (or something like that) is such a temporary one way street. (Day 1 - Route 3 of our test rides)

**Comment by PhilippMatthes** [comment]
Need to do some investigation first: find out which classes are used and how OSM maps time-sensitive access.

**Comment by PhilippMatthes** [comment]
Found out that DRN doesn't capture time restriction of Sierichstraße and Herbert-Weichmannstraße. Reported to Hamburg and now waiting for response.

**Comment by PhilippMatthes** [comment]
DRN was updated by LGV, now I can figure out a way to parse the time restriction.

**Comment by PhilippMatthes** [comment]
OSM captures Sierichstraße under [oneway:conditional](https://wiki.openstreetmap.org/wiki/DE:Key:oneway:conditional?uselang=de) = `yes @ (12:00-04:00); -1 @ (04:00-12:00)`

**Comment by PhilippMatthes** [comment]
See https://github.com/graphhopper/graphhopper/issues/374#issuecomment-370199976

It seems not to be possible to pass a time restriction to GraphHopper.

**Comment by PhilippMatthes** [comment]
Discussion with my team resulted in the following solution:
- Contributing a time access parser to GraphHopper is likely not a good choice, since the access also depends on the user's time of arrival. It's also an edge case that roads are only accessible at some daytimes.
- Instead, we choose to discard time-restricted ways.

**Comment by PhilippMatthes** [comment]
Reopening until updated in release.
